dependencies:
  - python=3.8
  - ipywidgets==7.5.1
  - jupyterlab==2.2.6
  - jupyterhub-singleuser==1.1.0
  - nbconvert==5.6.1
  - nbresuse==0.3.3
  - notebook==6.1.1
  - nteract_on_jupyter==2.1.3
  - numpy==1.19.1
  - scipy==1.5.0
  - pip==20.2.2
  - pip:
    - pandas==0.25.3
    - matplotlib==3.3.1